version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: twitter
       MYSQL_USER: root
       MYSQL_PASSWORD: root

   twitter:
     depends_on:
       - db
     image: tomee:latest
     volumes:
       - ./tomee:/usr/local/tomee/webapps/

     ports:
       - "8282:8080"
     restart: always
     environment:
       TOMEE_DB_HOST: db:3306
       TOMEE_DB_USER: twitter
       TOMEE_DB_PASSWORD: twitter
       TOMEE_DB_NAME: twitter
volumes:
    db_data: {}
    